title: Franska kaffihÃºsiÃ°

contact:
  en:
    phone: Phone
    email: Email
    address: Address
  en:
    phone: SÃ­ma
    email: TÃ¶lvupÃ³sti
    address: Heimilisfang
  tel: +354 123 4567
  email: contact@franskakaffihusid.is
  address: Kirkjuvammur,<br/>451 RauÃ°asandur,<br/>VesturbyggÃ°
  map: https://osm.org/go/efmp~2u?m=

languages: ["en", "is"]
exclude_from_localizations: ["assets"]
defaultLang: en
languageNames:
  en: English
  is: Ãslensku
languageIcons:
  en: ğŸ‡¬ğŸ‡§
  is: ğŸ‡®ğŸ‡¸

defaults:
  - scope:
      path: "assets/photos"
    values:
      image: true

season:
  start:
    month: "06"
    day: "01"
  end:
    month: "08"
    day: "31"

times:
  - open: "12:00"
    close: "20:00"
  - open: "12:00"
    close: "20:00"
  - open: "12:00"
    close: "20:00"
  - open: "12:00"
    close: "20:00"
  - open: "12:00"
    close: "20:00"
  - open: "12:00"
    close: "20:00"
  - open: "12:00"
    close: "20:00"

# Pastel
# colors:
#   background: "#FDF6EC"
#   primary: "#DAB88B"
#   secondary: "#F3E9DD"
#   accent: "#B7CADB"
  
# Contrast
# colors:
#   background: "#FDE1CB"
#   primary: "#B78365"
#   secondary: "#F1CCB1"
#   accent: "#84ABD7"

# Combined
# colors:
#   background: "#EBD6C2"
#   primary: "#996633"
#   secondary: "#E0C2A3"
#   accent: "#6699CC"

# Aquarel
colors:
  background: "#c7d5e1"
  primary: "#2e3d56"
  secondary: "#9fb6d3"
  accent: "#da9962"
